version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    privileged: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    privileged: true
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager.yml
    command:
      - '--config.file=/alertmanager.yml'
    ports:
      - '9093:9093'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
