version: '3'
services:
  backend:
    image: ${DOCKER_IMAGE_Back_NAME}
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - mysql

  frontend:
    image: ${DOCKER_IMAGE_Front_NAME}
    ports:
      - "8087:8087"
    depends_on:
      - backend

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=devops
    ports:
      - "3306:3306"  

    
