global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - prometheus:9090
      - node-exporter:9100
      - pushgateway:9091

  - job_name: Jenkins
    metrics_path: /prometheus
    static_configs:
    - targets: ['192.168.33.10:8080']

  - job_name: Devops_project
    metrics_path: /prometheus
    static_configs:
    - targets: ['192.168.33.10:8087']
    
  - job_name: backend
    scrape_interval: 5s
    metrics_path: /actuator/prometheus  # Le chemin où votre application expose les métriques
    static_configs:
  - targets: ['192.168.33.10:8083']  # Remplacez "backend-container-ip" par l'adresse IP du conteneur Backend

  - job_name: mysql
    scrape_interval: 5s
    metrics_path: /actuator/prometheus  # Le chemin où votre application expose les métriques
    static_configs:
    - targets: ['mysql:3306']  # Remplacez "backend-container-ip" par l'adresse IP du conteneur Backend

